# Mosquitto config for TLS baseline benchmark
# Plain MQTT on 1883 (already running as service)
listener 1883
allow_anonymous true

# TLS on 8883
listener 8883
cafile D:\Spring 2026\Internet of Things\IOT class Project\certs\ca.crt
certfile D:\Spring 2026\Internet of Things\IOT class Project\certs\server.crt
keyfile D:\Spring 2026\Internet of Things\IOT class Project\certs\server.key
require_certificate false
allow_anonymous true
